### ISSUE TITLE
Songs zu einer playlist hinzufügen

### ISSUE THREAD

**Issue by JamesWahlet** [MissingCore/Music#80] opened 2024-09-01 19:31 UTC
A multiple selection would be very helpful and great if you want to add songs to a playlist so that you can move multiple songs into a playlist at the same time.

**Comment by cyanChill** [comment] 2024-09-06 18:53
Duplicate of #76. Look at that discussion for updates on a potential swipe feature.

For future reference, this should have been a discussion instead of an issue.

**Closed by cyanChill** 2024-09-06 18:53 UTC
Labels: duplicate
