### ISSUE TITLE
No Tracks found / Folder is empty

### ISSUE THREAD

**Issue by learning-thing** [MissingCore/Music#39] opened 2024-07-23 10:32 UTC
### What device did this occur on?

Nothing Phone (2a)

### What version of Android is your device running?

Nothing os 2.6 (Android 14)

### App Version

Version v1.0.0-rc10

### Summary

There are a bunch of mp3 Files in my music folder, but the app tells me 
that there are no tracks.

### Screenshot / Video

![Screenshot_20240723-123137](https://github.com/user-attachments/assets/e6880eab-3818-4692-8857-4dd6a6a35cac)

**Comment by cyanChill** [comment] 2024-07-23 22:38
Some debugging suggestions:
1. Check the `TRACKS` tab to see if any tracks are displayed.
  a. This is to see if the issue is due to maybe me messing up the filtering logic for displaying tracks for this feature.
2. Go to the `INSIGHTS` screen from the settings page and send a screenshot.
  a. We want to see the value next to the "Save Error" statistic to see if at least the tracks were detected, but rejected for some reason.
3. Try clearing the app storage to force re-indexing.
  a. There might be some random issue with saving the first time.

If the tracks were detected but rejected, I think I might know the reason why: I currently have in the `@missingcore/audio-metadata` package to throw an error if a track has no tags, which I kind of forgot about. This **should be fixed in `v1.0.0-rc.11`** when I change what we use for reading the metadata, which should be faster than what we have currently.

**Comment by learning-thing** [comment] 2024-07-25 07:15
1. `Tracks` tab also shows "folder is empty"

2. Insights shows 8 save erors (I have 8 audio files) 
![Screenshot_20240724-125255](https://github.com/user-attachments/assets/29632ba9-9431-4d82-bf4d-5bcc876b30eb)

3. Tried alot of reinstalling/clearing didn't make a difference

**Closed** 2024-07-27 01:37 UTC
Labels: Bug, Issue Accepted

**Comment by cyanChill** [comment] 2024-08-09 20:38
@learning-thing @Avichal1234 `v1.0.0-rc.11` has been released and should fix the potential causes for the problem.
- We now use an Android API for getting the metadata of tracks (previous was manual logic).
- We add a new allowlist/blocklist feature in case your music isn't located in the `Music` directory on your device.
